1.Import pandas

In [1]:
import pandas as pd

2.Loading the xls file

In [14]:
import pandas as pd

df_raw = pd.read_excel("APP-CTC-2026.xls", header=None)

3. Data Inspection

In [15]:
df_raw.head(25)

,0,1
0,GUIDE ON HOW TO FILL IN THE TEMPLATE,NaN
1,In order to fill in the APP template you must ...,NaN
2,DO NOT change the template's format,NaN
3,DO NOT change the order of columns,NaN
4,DO NOT change the column headers,NaN
5,DO NOT leave empty rows,NaN
6,Fields in red highlight indicate mandatory fie...,NaN
7,Cells B1-B7 are optional and must be filled in...,NaN
8,"If uncertain or requiring help, please consult...",NaN
9,The rules to complete the template for creatin...,NaN
10,"Fill in the ""Data"" sheet of the APP template s...",NaN
11,NaN,NaN
12,Field,Validation Type
13,Class,"Mandatory, values: Goods, Works, Non Consultin..."
14,UNSPSC,"Mandatory, 8 digit UNSPSC Code"
15,IFMIS GL Account,Mandatory
16,Description,Mandatory
17,Ref No,"Mandatory, use by MDA"
18,Project Code,"Optional, for Project Procurement tracking"
19,Unit of Measure,Optional
20,Quantity,Optional
21,ZMW Estimated Budget - GOZ,Mandatory
22,ZMW Estimated Budget - Other,Optional
23,ZMW Estimated Budget - Total,Mandatory
24,$FX Budget Amount - Currency,Optional

Show the column names

In [16]:
for i in range(25):
    print(i, df_raw.iloc[i].tolist())

0 ['GUIDE ON HOW TO FILL IN THE TEMPLATE', nan]
1 ['In order to fill in the APP template you must save it in MS XLS or XLSX format', nan]
2 ["DO NOT change the template's format", nan]
3 ['DO NOT change the order of columns', nan]
4 ['DO NOT change the column headers', nan]
5 ['DO NOT leave empty rows', nan]
6 ['Fields in red highlight indicate mandatory fields, while fields in yellow highlight indicate fields that are optional', nan]
7 ['Cells B1-B7 are optional and must be filled in manually', nan]
8 ['If uncertain or requiring help, please consult the Buyer User Manual', nan]
9 ['The rules to complete the template for creating a valid APP are listed below', nan]
10 ['Fill in the "Data" sheet of the APP template starting from Row 11', nan]
11 [nan, nan]
12 ['Field', 'Validation Type']
13 ['Class', 'Mandatory, values: Goods, Works, Non Consulting Services, Consulting Services']
14 ['UNSPSC', 'Mandatory, 8 digit UNSPSC Code ']
15 ['IFMIS GL Account', 'Mandatory']
16 ['Description', 'Mandatory']
17 ['Ref No', 'Mandatory,  use by MDA']
18 ['Project Code', 'Optional, for Project Procurement tracking']
19 ['Unit of Measure', 'Optional']
20 ['Quantity', 'Optional']
21 ['ZMW Estimated Budget - GOZ', 'Mandatory']
22 ['ZMW Estimated Budget - Other', 'Optional']
23 ['ZMW Estimated Budget - Total', 'Mandatory']
24 ['$FX Budget Amount - Currency', 'Optional']

In [17]:
xls = pd.ExcelFile("APP-CTC-2026.xls")

print(xls.sheet_names)

['Information', 'Data']

Loading the sheet with NO header because It does not have clear rows , and colums

In [18]:
df_raw = pd.read_excel(
    "APP-CTC-2026.xls",
    sheet_name="Data",
    header=None
)

In [19]:
df_raw.head(25)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Entity,CHIRUNDU TOWN COUNCIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Procurement Plan for year,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Version,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Procurement Budget,60450703.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZMW Control Total,60500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Date Last Updated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Comments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZMW Estimated Budget,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Class,UNSPSC,IFMIS GL Account,Description,Ref No,Project Code,Unit of Measure,Quantity,GOZ,Other,...,Award,Start,Public View (Y/N),Public View Justification,Comments,Source,Project ID,URI,Rationale,Type of Entry
10,Goods,43210000,0,"Procurement of computer peripherals, equipment...",1,NaN,each,NaN,757469,NaN,...,2026-02-16 00:00:00,2026-02-18 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
11,Goods,14111509,0,"Procurement of office stationery, tonners, boo...",2,NaN,each,NaN,1000000,NaN,...,2026-01-26 00:00:00,2026-02-02 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
12,Goods,14111509,0,"Procurement of office stationery, tonners, boo...",3,NaN,each,NaN,579690,NaN,...,2026-06-28 00:00:00,2026-02-03 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
13,Goods,56000000,0,"Procurement of Office furnitures for Audit, Pr...",4,NaN,each,NaN,1000000,NaN,...,2026-03-02 00:00:00,2026-03-06 00:00:00,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
14,Goods,56000000,0,Procurement of Office furnitures under Adminis...,5,NaN,each,NaN,218800,NaN,...,2026-05-25 00:00:00,2026-06-02 00:00:00,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
15,Goods,47000000,0,Procurement of cleaning materials,6,NaN,each,NaN,52440,NaN,...,2026-01-30 00:00:00,2026-02-02 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
16,Consulting services,72102305,0,Servicing of air conditioners for the Council ...,7,NaN,each,NaN,78862,NaN,...,2026-03-27 00:00:00,2026-03-31 00:00:00,Y,NaN,NaN,NaN,NaN,NaN,NaN,A
17,Works,72100000,0,Building maintenance,8,NaN,each,NaN,40000,NaN,...,2026-05-07 00:00:00,2026-05-13 00:00:00,Y,NaN,NaN,NaN,NaN,NaN,NaN,A
18,Goods,53103000,0,Procurement of T Shirts and Banners for public...,9,NaN,each,NaN,440050,NaN,...,2026-02-27 00:00:00,2026-03-02 00:00:00,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
19,Non Consulting services,56121400,0,Procurement of refreshments for the various in...,10,NaN,each,NaN,820660,NaN,...,2026-01-30 00:00:00,2026-02-02 00:00:00,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
20,Goods,22101603,0,Procurement of fuel under RTSA for grading of ...,11,NaN,each,NaN,777000,NaN,...,2026-04-22 00:00:00,2026-05-04 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
21,Non Consulting services,39000000,0,Procurement of Zesco Units for the Council Off...,12,NaN,each,NaN,219000,NaN,...,2026-01-29 00:00:00,2026-02-01 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
22,Consulting services,78180100,0,Motor Vehicle maintence,13,NaN,each,NaN,878000,NaN,...,2026-01-05 00:00:00,2026-02-09 00:00:00,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
23,Goods,25173107,0,Procurement of handle GPS for Public Relations...,14,NaN,each,NaN,32000,NaN,...,2026-06-10 00:00:00,2026-06-12 00:00:00,Y,NaN,NaN,NaN,NaN,NaN,NaN,A
24,Goods,15100000,0,Procurement of fuel for other activities Counc...,15,NaN,each,NaN,1000000,NaN,...,2026-01-30 00:00:00,2026-02-01 00:00:00,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A

Displaying it more clearly , in order to help identify the exact headers

In [21]:
for i in range(25):
    print(i, df_raw.iloc[i].tolist())

0 ['Entity', 'CHIRUNDU TOWN COUNCIL', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
1 ['Procurement Plan for year', 2026, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
2 ['Version', 1, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
3 ['Procurement Budget', 60450703.06000001, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
4 ['ZMW Control Total', 60500000, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
5 ['Date Last Updated', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
6 ['Comments', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
7 [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
8 [nan, nan, nan, nan, nan, nan, nan, nan, 'ZMW Estimated Budget ', nan, nan, 'FX Budget Amount', nan, nan, nan, nan, 'Estimated dates', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
9 ['Class', 'UNSPSC', 'IFMIS GL Account', 'Description', 'Ref No', 'Project Code', 'Unit of Measure', 'Quantity', 'GOZ', 'Other', 'Total', 'Currency', 'Amount', 'Source of Funds', 'Prequalification (Y/N)', 'Procurement Method', 'Publication', 'Award  ', 'Start ', 'Public View (Y/N)', 'Public View Justification', 'Comments', 'Source', 'Project ID', 'URI', 'Rationale', 'Type of Entry']
10 ['Goods', '43210000', 0, 'Procurement of computer peripherals, equipments and accessories', 1, nan, 'each', nan, 757469, nan, 757469, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 21, 0, 0), datetime.datetime(2026, 2, 16, 0, 0), datetime.datetime(2026, 2, 18, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
11 ['Goods', 14111509, 0, 'Procurement of office stationery, tonners, books, files and other accessories ', 2, nan, 'each', nan, 1000000, nan, 1000000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 22, 0, 0), datetime.datetime(2026, 1, 26, 0, 0), datetime.datetime(2026, 2, 2, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
12 ['Goods', 14111509, 0, 'Procurement of office stationery, tonners, books, files and other accessories (Additional)', 3, nan, 'each', nan, 579690, nan, 579690, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 23, 0, 0), datetime.datetime(2026, 6, 28, 0, 0), datetime.datetime(2026, 2, 3, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
13 ['Goods', 56000000, 0, 'Procurement of Office furnitures for Audit, Procurement Unit and Finance dept (2026)', 4, nan, 'each', nan, 1000000, nan, 1000000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 2, 25, 0, 0), datetime.datetime(2026, 3, 2, 0, 0), datetime.datetime(2026, 3, 6, 0, 0), 'Y', nan, 'quartely procurements', nan, nan, nan, nan, 'A']
14 ['Goods', 56000000, 0, 'Procurement of Office furnitures under Administration Dept (2026)', 5, nan, 'each', nan, 218800, nan, 218800, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 5, 18, 0, 0), datetime.datetime(2026, 5, 25, 0, 0), datetime.datetime(2026, 6, 2, 0, 0), 'Y', nan, 'quartely procurements', nan, nan, nan, nan, 'A']
15 ['Goods', 47000000, 0, 'Procurement of cleaning materials', 6, nan, 'each', nan, 52440, nan, 52440, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 26, 0, 0), datetime.datetime(2026, 1, 30, 0, 0), datetime.datetime(2026, 2, 2, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
16 ['Consulting services', 72102305, 0, 'Servicing of air conditioners for the Council Offices', 7, nan, 'each', nan, 78862, nan, 78862, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 3, 24, 0, 0), datetime.datetime(2026, 3, 27, 0, 0), datetime.datetime(2026, 3, 31, 0, 0), 'Y', nan, nan, nan, nan, nan, nan, 'A']
17 ['Works', 72100000, 0, 'Building maintenance', 8, nan, 'each', nan, 40000, nan, 40000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 5, 4, 0, 0), datetime.datetime(2026, 5, 7, 0, 0), datetime.datetime(2026, 5, 13, 0, 0), 'Y', nan, nan, nan, nan, nan, nan, 'A']
18 ['Goods', 53103000, 0, 'Procurement of T Shirts and Banners for public events commemorations', 9, nan, 'each', nan, 440050, nan, 440050, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 2, 24, 0, 0), datetime.datetime(2026, 2, 27, 0, 0), datetime.datetime(2026, 3, 2, 0, 0), 'Y', nan, 'quartely procurements', nan, nan, nan, nan, 'A']
19 ['Non Consulting services', 56121400, 0, 'Procurement of refreshments for the various institutional management and committee meetings', 10, nan, 'each', nan, 820660, nan, 820660, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 26, 0, 0), datetime.datetime(2026, 1, 30, 0, 0), datetime.datetime(2026, 2, 2, 0, 0), 'Y', nan, 'quartely procurements', nan, nan, nan, nan, 'A']
20 ['Goods', 22101603, 0, 'Procurement of fuel under RTSA for grading of township roads', 11, nan, 'each', nan, 777000, nan, 777000, nan, nan, 'RTSA', 'N', 'db', datetime.datetime(2026, 4, 15, 0, 0), datetime.datetime(2026, 4, 22, 0, 0), datetime.datetime(2026, 5, 4, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
21 ['Non Consulting services', 39000000, 0, 'Procurement of Zesco Units for the Council Offices', 12, nan, 'each', nan, 219000, nan, 219000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 1, 26, 0, 0), datetime.datetime(2026, 1, 29, 0, 0), datetime.datetime(2026, 2, 1, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']
22 ['Consulting services', 78180100, 0, 'Motor Vehicle maintence', 13, nan, 'each', nan, 878000, nan, 878000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 2, 2, 0, 0), datetime.datetime(2026, 1, 5, 0, 0), datetime.datetime(2026, 2, 9, 0, 0), 'Y', nan, 'quartely procurements', nan, nan, nan, nan, 'A']
23 ['Goods', 25173107, 0, 'Procurement of handle GPS for Public Relations Unit', 14, nan, 'each', nan, 32000, nan, 32000, nan, nan, 'Local Revenue', 'N', 'sb', datetime.datetime(2026, 6, 8, 0, 0), datetime.datetime(2026, 6, 10, 0, 0), datetime.datetime(2026, 6, 12, 0, 0), 'Y', nan, nan, nan, nan, nan, nan, 'A']
24 ['Goods', 15100000, 0, 'Procurement of fuel for other activities Council Operations under Administration Dept', 15, nan, 'each', nan, 1000000, nan, 1000000, nan, nan, 'Local Revenue', 'N', 'db', datetime.datetime(2026, 1, 27, 0, 0), datetime.datetime(2026, 1, 30, 0, 0), datetime.datetime(2026, 2, 1, 0, 0), 'Y', nan, 'monthly procurements', nan, nan, nan, nan, 'A']

Find the word Class

In [22]:
for row in range(len(df_raw)):
    for col in range(len(df_raw.columns)):
        if str(df_raw.iloc[row, col]).strip().lower() == "class":
            print("Class found at row:", row, "column:", col)

Class found at row: 9 column: 0

In [23]:
df = pd.read_excel(
    "APP-CTC-2026.xls",
    sheet_name="Data",
    header=9
)

In [24]:
df.columns.tolist()

['Class',
 'UNSPSC',
 'IFMIS GL Account',
 'Description',
 'Ref No',
 'Project Code',
 'Unit of Measure',
 'Quantity',
 'GOZ',
 'Other',
 'Total',
 'Currency',
 'Amount',
 'Source of Funds',
 'Prequalification (Y/N)',
 'Procurement Method',
 'Publication',
 'Award  ',
 'Start ',
 'Public View (Y/N)',
 'Public View Justification',
 'Comments',
 'Source',
 'Project ID',
 'URI',
 'Rationale',
 'Type of Entry']

In [26]:
df.head()

,Class,UNSPSC,IFMIS GL Account,Description,Ref No,Project Code,Unit of Measure,Quantity,GOZ,Other,...,Award,Start,Public View (Y/N),Public View Justification,Comments,Source,Project ID,URI,Rationale,Type of Entry
0,Goods,43210000,0,"Procurement of computer peripherals, equipment...",1,NaN,each,NaN,757469.0,NaN,...,2026-02-16,2026-02-18,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
1,Goods,14111509,0,"Procurement of office stationery, tonners, boo...",2,NaN,each,NaN,1000000.0,NaN,...,2026-01-26,2026-02-02,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
2,Goods,14111509,0,"Procurement of office stationery, tonners, boo...",3,NaN,each,NaN,579690.0,NaN,...,2026-06-28,2026-02-03,Y,NaN,monthly procurements,NaN,NaN,NaN,NaN,A
3,Goods,56000000,0,"Procurement of Office furnitures for Audit, Pr...",4,NaN,each,NaN,1000000.0,NaN,...,2026-03-02,2026-03-06,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A
4,Goods,56000000,0,Procurement of Office furnitures under Adminis...,5,NaN,each,NaN,218800.0,NaN,...,2026-05-25,2026-06-02,Y,NaN,quartely procurements,NaN,NaN,NaN,NaN,A

In [27]:
for col in df.columns:
    print(repr(col))

'Class'
'UNSPSC'
'IFMIS GL Account'
'Description'
'Ref No'
'Project Code'
'Unit of Measure'
'Quantity'
'GOZ'
'Other'
'Total'
'Currency'
'Amount'
'Source of Funds'
'Prequalification (Y/N)'
'Procurement Method'
'Publication'
'Award  '
'Start '
'Public View (Y/N)'
'Public View Justification'
'Comments'
'Source'
'Project ID'
'URI'
'Rationale'
'Type of Entry'

In [28]:
df_mined = df[
    [
        "Class",
        "Description",
        "Total",
        "Source of Funds",
        "Procurement Method",
        "Start "
    ]
]

In [29]:
df_mined = df_mined.rename(columns={
    "Class": "Category",
    "Description": "Procurement item",
    "Total": "Estimated Amount",
    "Source of Funds": "Source of Funds",
    "Procurement Method": "Procurement Method",
    "Start ": "date"
})

In [30]:
df_mined.head()

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
0,Goods,"Procurement of computer peripherals, equipment...",757469.0,Local Revenue,sb,2026-02-18
1,Goods,"Procurement of office stationery, tonners, boo...",1000000.0,Local Revenue,sb,2026-02-02
2,Goods,"Procurement of office stationery, tonners, boo...",579690.0,Local Revenue,sb,2026-02-03
3,Goods,"Procurement of Office furnitures for Audit, Pr...",1000000.0,Local Revenue,sb,2026-03-06
4,Goods,Procurement of Office furnitures under Adminis...,218800.0,Local Revenue,sb,2026-06-02

In [31]:
df_mined.columns.tolist()

['Category',
 'Procurement item',
 'Estimated Amount',
 'Source of Funds',
 'Procurement Method',
 'date']

In [32]:
df_mined.shape

(60, 6)

In [33]:
df_mined.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Category            60 non-null     str
 1   Procurement item    60 non-null     str
 2   Estimated Amount    60 non-null     float64
 3   Source of Funds     60 non-null     str
 4   Procurement Method  60 non-null     str
 5   date                60 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 2.9 KB

In [34]:
df_mined.isnull().sum()

Category              0
Procurement item      0
Estimated Amount      0
Source of Funds       0
Procurement Method    0
date                  0
dtype: int64

In [35]:
df_mined.head(10)

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
0,Goods,"Procurement of computer peripherals, equipment...",757469.0,Local Revenue,sb,2026-02-18
1,Goods,"Procurement of office stationery, tonners, boo...",1000000.0,Local Revenue,sb,2026-02-02
2,Goods,"Procurement of office stationery, tonners, boo...",579690.0,Local Revenue,sb,2026-02-03
3,Goods,"Procurement of Office furnitures for Audit, Pr...",1000000.0,Local Revenue,sb,2026-03-06
4,Goods,Procurement of Office furnitures under Adminis...,218800.0,Local Revenue,sb,2026-06-02
5,Goods,Procurement of cleaning materials,52440.0,Local Revenue,sb,2026-02-02
6,Consulting services,Servicing of air conditioners for the Council ...,78862.0,Local Revenue,sb,2026-03-31
7,Works,Building maintenance,40000.0,Local Revenue,sb,2026-05-13
8,Goods,Procurement of T Shirts and Banners for public...,440050.0,Local Revenue,sb,2026-03-02
9,Non Consulting services,Procurement of refreshments for the various in...,820660.0,Local Revenue,sb,2026-02-02

Converting estimated amount to Numeric

In [36]:
df_mined["Estimated Amount"] = pd.to_numeric(
    df_mined["Estimated Amount"],
    errors="coerce"
)

In [37]:
df_mined["Estimated Amount"].head()

0     757469.0
1    1000000.0
2     579690.0
3    1000000.0
4     218800.0
Name: Estimated Amount, dtype: float64

Coverting the date column

In [38]:
df_mined["date"] = pd.to_datetime(
    df_mined["date"],
    errors="coerce"
)

In [39]:
df_mined["date"].head()

0   2026-02-18
1   2026-02-02
2   2026-02-03
3   2026-03-06
4   2026-06-02
Name: date, dtype: datetime64[us]

Removal of completely empty Procurement records

In [40]:
df_mined = df_mined.dropna(
    subset=["Category", "Procurement item"],
    how="all"
)

Reset the index

In [41]:
df_mined = df_mined.reset_index(drop=True)

Checking the info

In [42]:
df_mined.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Category            60 non-null     str
 1   Procurement item    60 non-null     str
 2   Estimated Amount    60 non-null     float64
 3   Source of Funds     60 non-null     str
 4   Procurement Method  60 non-null     str
 5   date                60 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 2.9 KB

In [43]:
df_mined.head(10)

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
0,Goods,"Procurement of computer peripherals, equipment...",757469.0,Local Revenue,sb,2026-02-18
1,Goods,"Procurement of office stationery, tonners, boo...",1000000.0,Local Revenue,sb,2026-02-02
2,Goods,"Procurement of office stationery, tonners, boo...",579690.0,Local Revenue,sb,2026-02-03
3,Goods,"Procurement of Office furnitures for Audit, Pr...",1000000.0,Local Revenue,sb,2026-03-06
4,Goods,Procurement of Office furnitures under Adminis...,218800.0,Local Revenue,sb,2026-06-02
5,Goods,Procurement of cleaning materials,52440.0,Local Revenue,sb,2026-02-02
6,Consulting services,Servicing of air conditioners for the Council ...,78862.0,Local Revenue,sb,2026-03-31
7,Works,Building maintenance,40000.0,Local Revenue,sb,2026-05-13
8,Goods,Procurement of T Shirts and Banners for public...,440050.0,Local Revenue,sb,2026-03-02
9,Non Consulting services,Procurement of refreshments for the various in...,820660.0,Local Revenue,sb,2026-02-02

Creation of the csv file.

In [44]:
df_mined.to_csv(
    "chirundu_procurement_2026.csv",
    sep="|",
    index=False
)

Confirming if the file was created

In [45]:
import os

print(os.path.exists("chirundu_procurement_2026.csv"))

True